name: weather_app_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_native_splash: ^2.4.7
  hooks_riverpod: 3.1.0
  riverpod_annotation: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.11.1

  
flutter:
  uses-material-design: true

  assets:
    - assets/MainWeather.png

