name: weather_app_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_native_splash: ^2.4.7
  freezed_annotation: ^3.1.0
  hooks_riverpod: 3.1.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.11.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true

  assets:
    - assets/MainWeather.png
